name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
    paths:
      - 'docs/**'
      
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy Markdown File to _site
        run: |
          mkdir -p _site
          cp docs/index.md _site/index.md
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Show deployment URL
        run: echo "Deployment successful! Visit your site at https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
