name: Metrics
on:
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_contributors: yes
          plugin_contributors_sections: categories
          plugin_contributors_categories: |
            {
                "🧩 Plugins / 🖼️ templates":["source/plugins/**", "source/templates/**"],
                "📚 Documentation":["README.md", "**/README.md", "**/metadata.yml"],
                "💻 Code (other)":["source/**", "Dockerfile"]
            }
