name: Build Rust Release

on:
  pull_request:
    paths:
      - '**/*.rs'
      - 'Cargo.toml'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build release binary
        run: |
          cargo build --release || { echo "Build failed"; exit 1; }
          if [ -f target/release/carch ]; then
              mkdir -p build
              mv target/release/carch ./build/carch
          else
              echo "Binary not found. Build may have failed."
              exit 1
          fi
          rm -rf target/release  # Optional: remove the target/release directory

      - name: List build artifacts
        run: ls ./build

      - name: Upload Release Binary
        uses: actions/upload-artifact@v3
        with:
          name: rust-release-binary
          path: ./build/carch
