name: Upload Scripts Zip to Latest Release

on:
  push:
    paths:
      - "scripts/*.sh"

jobs:
  upload_zip_to_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install GitHub CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y gh

    - name: Authenticate GitHub CLI
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "${GITHUB_TOKEN}" | gh auth login --with-token

    - name: Confirm Zip File Exists
      run: |
        if [ ! -f zip/carchscripts.zip ]; then
          echo "Error: zip/carchscripts.zip does not exist."
          exit 1
        fi
        echo "File found: zip/carchscripts.zip"
    
    - name: Debug File Path and Size
      run: |
        ls -lh zip/carchscripts.zip
        file zip/carchscripts.zip

    - name: Get Latest Release Tag
      id: get_release
      run: |
        latest_tag=$(gh release list --limit 1 --json tagName --jq '.[0].tagName')
        echo "tag=$latest_tag" >> $GITHUB_ENV

    - name: Upload Zip File to Latest Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload "$tag" zip/carchscripts.zip --clobber
