name: Upload Scripts Zip to Latest Release

on:
  push:
    paths:
      - "scripts/*.sh"  # Trigger only if there's a change in any .sh file in the `scripts` directory.

jobs:
  upload_zip_to_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Get Latest Release
      id: get_latest_release
      uses: actions/github-script@v6
      with:
        script: |
          const latestRelease = await github.rest.repos.getLatestRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
          });
          core.setOutput("release_id", latestRelease.data.id);

    - name: Upload Zip File to Latest Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: zip/carchscripts.zip
        tag: ${{ steps.get_latest_release.outputs.release_id }}
        token: ${{ secrets.GITHUB_TOKEN }}
