name: Upload Scripts Zip to Latest Release

on:
  push:
    paths:
      - "scripts/*.sh"  # Trigger only if there's a change in any .sh file in the `scripts` directory.

jobs:
  upload_zip_to_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install GitHub CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y gh

    - name: Authenticate GitHub CLI
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "${GITHUB_TOKEN}" | gh auth login --with-token

    - name: Get Latest Release Tag
      id: get_release
      run: |
        latest_tag=$(gh release list --limit 1 --json tagName --jq '.[0].tagName')
        echo "tag=$latest_tag" >> $GITHUB_ENV

    - name: Upload Zip File to Latest Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload "${tag}" zip/carchscripts.zip --clobber
