name: Update Scripts Zip in Latest Release

on:
  push:
    paths:
      - "scripts/*.sh"  # Trigger only if there's a change in any .sh file in the `scripts` directory.

jobs:
  upload_zip_to_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Get Latest Release Upload URL
      id: get_latest_release_upload_url
      uses: actions/github-script@v6
      with:
        script: |
          const latestRelease = await github.rest.repos.getLatestRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
          });
          // Output both the release ID and the correct upload URL
          core.setOutput("release_id", latestRelease.data.id);
          core.setOutput("upload_url", latestRelease.data.upload_url.split("{")[0]);  // Remove "{?name,label}"

    - name: Delete Existing Zip Asset (if any)
      uses: actions/github-script@v6
      with:
        script: |
          const releaseId = ${{ steps.get_latest_release_upload_url.outputs.release_id }};
          const assets = await github.rest.repos.listReleaseAssets({
            owner: context.repo.owner,
            repo: context.repo.repo,
            release_id: releaseId,
          });
          for (const asset of assets.data) {
            if (asset.name === "carchscripts.zip") {
              await github.rest.repos.deleteReleaseAsset({
                owner: context.repo.owner,
                repo: context.repo.repo,
                asset_id: asset.id,
              });
            }
          }

    - name: Upload New Zip Asset to Latest Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.get_latest_release_upload_url.outputs.upload_url }}  # Corrected URL without release ID
        asset_path: "zip/carchscripts.zip"  # Path to the zip file
        asset_name: "carchscripts.zip"
        asset_content_type: application/zip
