name: Upload Scripts Zip to Latest Release

on:
  push:
    paths:
      - "scripts/*.sh"  # Trigger only if there's a change in any .sh file in the `scripts` directory.

permissions:
  contents: write  # Grant permissions to modify release contents

jobs:
  upload_zip_to_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Extract Version
      id: extract_version
      run: |
        # Use date as the version or set any versioning format you prefer
        version=$(date +"%Y.%m.%d")
        echo "version=$version" >> $GITHUB_ENV
      shell: bash

    - name: Create and Upload Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.version }}
        name: Release ${{ env.version }}
        files: zip/carchscripts.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
