name: Upload Scripts Zip to Latest Release

on:
  push:
    paths:
      - "scripts/*.sh"  # Trigger only if there's a change in any .sh file in the `scripts` directory.

jobs:
  upload_zip_to_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Get Latest Release Upload URL
      id: get_latest_release_upload_url
      uses: actions/github-script@v6
      with:
        script: |
          const latestRelease = await github.rest.repos.getLatestRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
          });
          // Output the upload_url (without {name,label} part)
          core.setOutput("upload_url", latestRelease.data.upload_url.split("{")[0]);

    - name: Upload Zip File to Latest Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.get_latest_release_upload_url.outputs.upload_url }}  # Correct URL without {name,label}
        asset_path: "zip/carchscripts.zip"  # Path to the zip file
        asset_name: "carchscripts.zip"
        asset_content_type: application/zip
