name: Update Scripts Zip in Latest Release

on:
  push:
    paths:
      - "scripts/*.sh"  # Trigger only if there's a change in any .sh file in the `scripts` directory.

jobs:
  upload_zip_to_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Get Latest Release
      id: get_latest_release
      uses: actions/github-script@v6
      with:
        script: |
          const latestRelease = await github.rest.repos.getLatestRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
          });
          return latestRelease.data.id;

    - name: Delete Existing Zip Asset (if any)
      id: delete_asset
      uses: actions/github-script@v6
      with:
        script: |
          const releaseId = ${{ steps.get_latest_release.outputs.result }};
          const assets = await github.rest.repos.listReleaseAssets({
            owner: context.repo.owner,
            repo: context.repo.repo,
            release_id: releaseId,
          });
          for (const asset of assets.data) {
            if (asset.name === "scripts.zip") {
              await github.rest.repos.deleteReleaseAsset({
                owner: context.repo.owner,
                repo: context.repo.repo,
                asset_id: asset.id,
              });
            }
          }

    - name: Upload New Zip Asset to Latest Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.get_latest_release.outputs.result }}/assets{?name,label}
        asset_path: "zip/carchscripts.zip"  # Properly quoted path
        asset_name: "carchscripts.zip"  # Ensure asset name matches the file being uploaded
        asset_content_type: application/zip

